module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: [
    "ai",
    "ai-google-scholar",
    "ai-google-scholar-square",
    "fab",
    "fa",
    "fa-brands",
    "fa-envelope",
    "fa-envelope-square",
    "fa-github",
    "fa-github-square",
    "fa-linkedin",
    "fa-linkedin-in",
    "fa-regular",
    "fa-square-envelope",
    "fa-square-github",
    "fa-square-linkedin",
    "fa-solid",
    "far",
    "fas",
  ],
};
